### ISSUE TITLE
go-wkhtmltopdf missing wkhtmltox.dll

### ISSUE THREAD

**Issue by rickdana** [adrg/go-wkhtmltopdf#9]
Hello, 

I'm building a program using go-wkhtmltopdf. I followed the install guide and installed the [wkhtmltopdf ](https://wkhtmltopdf.org/downloads.html) as requested. 

When I run my program, I have the following err:
`the code cannot proceed because wkhtmltox.dll was not found. Reinstallling may ffix the problem`

Any Idea on how to tell  go-wkhtmltopdf where to find the requested dll? 
Bellow my go env output: 

```
set GO111MODULE=auto
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\xxx\AppData\Local\go-build
set GOENV=C:\Users\xxx\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\xx\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\xx\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Users\xx\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Users\xxx\go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\xxx\AppData\Local\Temp\go-build397288522=/tmp/go-build -gno-record-gcc-switches
```
PS: I'm using **mingw64**

**Comment by adrg** [comment]
Hi @rickdana. Thank you for your interest in the library. I made a quick test on Windows. 
Here are the steps I followed in order to build against the library on Windows.

1. Download the latest installation package from https://wkhtmltopdf.org/downloads.html.

![download](https://user-images.githubusercontent.com/6454770/110942867-1dbe7280-8343-11eb-9d2e-49bf5707fd5b.png)

2. Install wkhtmltopdf. I chose to install it in `C:\wkhtmltox`.

<img width="393" alt="install1" src="https://user-images.githubusercontent.com/6454770/110942971-40e92200-8343-11eb-936a-99eef4605c49.png">

The header files and the pre-built library can be found in the installation directory.

![install2](https://user-images.githubusercontent.com/6454770/110943114-7db51900-8343-11eb-9e94-68e773f75283.png)

3. Open a `cmd` instance, set `CGO_CFLAGS` and `CGO_LDFLAGS` to point to the installation directory paths and build your application.

```
set CGO_CFLAGS=-IC:\wkhtmltox\include
set CGO_LDFLAGS=-LC:\wkhtmltox\bin
go build
```

<img width="725" alt="build" src="https://user-images.githubusercontent.com/6454770/110943262-b05f1180-8343-11eb-87e3-242331d93a5d.png">

You can also copy `wkhtmltox.dll` from `C:\wkhtmltox\bin` to the directory where your binary is located instead of setting `CGO_LDFLAGS`.

**Comment by rickdana** [comment]
Hello @adrg, Thank for the quick support. 

I followed your advise and now I have the following output (see bellow).

Could you help me to interpret the err ? 

```
QEventLoop: Cannot be used without QApplication
Exception 0xc0000005 0x0 0x8 0x7ff8b6547110
PC=0x7ff8b6547110

runtime: unknown pc 0x7ff8b6547110
stack: frame={sp:0x75827fecb8, fp:0x0} stack=[0x0,0x75827ff700)
00000075827febb8:  0000000000000000  000001f6db310000 
00000075827febc8:  00000075827fec69  0000000000000003 
00000075827febd8:  00007ff9205fd997  0000007500000040 
00000075827febe8:  00007ff800000001  0000000000000028 
00000075827febf8:  0000007500000000  00000075827feca8 
00000075827fec08:  000001f6db3c2078  0000000000000002 
00000075827fec18:  fffffffffffffffe  000001f6db3b3b80 
00000075827fec28:  000001f6db3b5550  0000000000000000 
00000075827fec38:  000001f6db3b3b80  000001f6db3b5550 
00000075827fec48:  000001f6db3c1c01  000001f6db3c2078 
00000075827fec58:  00007ff8b58792ab  00000075827fece0 
00000075827fec68:  00000075827fece0  0000000000000000 
00000075827fec78:  0000000000000000  000001f600000000 
00000075827fec88:  0000000000000101  0000000000000000 
00000075827fec98:  000001f6db3a7560  000001f6db38bbb8 
00000075827feca8:  0000000000000000  000001f6db35e7a0 
00000075827fecb8: <00007ff8b591c532  00000075827feeb0 
00000075827fecc8:  00007ff91ce0ca26  0000000000000000 
00000075827fecd8:  0000000000000028  000001f6db3bc900 
00000075827fece8:  00007ff8b596284f  000001f6db35e7a0 
00000075827fecf8:  00007ff8b5769d3c  000001f6db35e7a0 
00000075827fed08:  000001f6db382780  fffffffffffffffe 
00000075827fed18:  0000000000000000  000001f6db35e7a0 
00000075827fed28:  00007ff8b5789083  000001f6db3bc900 
00000075827fed38:  0000000000000000  0000000000000000 
00000075827fed48:  000001f6db35e7a0  fffffffffffffffe 
00000075827fed58:  000001f6db3a7560  000001f6db382780 
00000075827fed68:  00007ff8b5752b38  000001f6db3bc900 
00000075827fed78:  00000075827feeb0  000001f6db35e7a0 
00000075827fed88:  0000000000000000  fffffffffffffffe 
00000075827fed98:  000001f6db3a7560  000001f6db3bd590 
00000075827feda8:  00007ff8b57ef292  000001f6db35e7a0 
runtime: unknown pc 0x7ff8b6547110
stack: frame={sp:0x75827fecb8, fp:0x0} stack=[0x0,0x75827ff700)
00000075827febb8:  0000000000000000  000001f6db310000 
00000075827febc8:  00000075827fec69  0000000000000003 
00000075827febd8:  00007ff9205fd997  0000007500000040 
00000075827febe8:  00007ff800000001  0000000000000028 
00000075827febf8:  0000007500000000  00000075827feca8 
00000075827fec08:  000001f6db3c2078  0000000000000002 
00000075827fec18:  fffffffffffffffe  000001f6db3b3b80 
00000075827fec28:  000001f6db3b5550  0000000000000000 
00000075827fec38:  000001f6db3b3b80  000001f6db3b5550 
00000075827fec48:  000001f6db3c1c01  000001f6db3c2078 
00000075827fec58:  00007ff8b58792ab  00000075827fece0 
00000075827fec68:  00000075827fece0  0000000000000000 
00000075827fec78:  0000000000000000  000001f600000000 
00000075827fec88:  0000000000000101  0000000000000000 
00000075827fec98:  000001f6db3a7560  000001f6db38bbb8 
00000075827feca8:  0000000000000000  000001f6db35e7a0 
00000075827fecb8: <00007ff8b591c532  00000075827feeb0 
00000075827fecc8:  00007ff91ce0ca26  0000000000000000 
00000075827fecd8:  0000000000000028  000001f6db3bc900 
00000075827fece8:  00007ff8b596284f  000001f6db35e7a0 
00000075827fecf8:  00007ff8b5769d3c  000001f6db35e7a0 
00000075827fed08:  000001f6db382780  fffffffffffffffe 
00000075827fed18:  0000000000000000  000001f6db35e7a0 
00000075827fed28:  00007ff8b5789083  000001f6db3bc900 
00000075827fed38:  0000000000000000  0000000000000000 
00000075827fed48:  000001f6db35e7a0  fffffffffffffffe 
00000075827fed58:  000001f6db3a7560  000001f6db382780 
00000075827fed68:  00007ff8b5752b38  000001f6db3bc900 
00000075827fed78:  00000075827feeb0  000001f6db35e7a0 
00000075827fed88:  0000000000000000  fffffffffffffffe 
00000075827fed98:  000001f6db3a7560  000001f6db3bd590 
00000075827feda8:  00007ff8b57ef292  000001f6db35e7a0 

goroutine 1 [syscall]:
github.com/adrg/go-wkhtmltopdf._Cfunc_wkhtmltopdf_convert(0x1f6db354470, 0xc000000000)
	_cgo_gotypes.go:123 +0x4b
github.com/adrg/go-wkhtmltopdf.(*Converter).Run.func1(0xc000360840, 0x0)
	C:/Users/xxxx/Go/pkg/mod/github.com/adrg/go-wkhtmltopdf@v0.2.2/converter.go:254 +0x65
github.com/adrg/go-wkhtmltopdf.(*Converter).Run(0xc000360840, 0x7ff771fcdba0, 0xc000236550, 0x1b6, 0xc000236550)
	C:/Users/xxxx/Go/pkg/mod/github.com/adrg/go-wkhtmltopdf@v0.2.2/converter.go:254 +0x8c
am-repport/pdf.(*WkHtmlGenerator).GeneratePDF(0xc000236530, 0xc00028aa00, 0x0, 0x0, 0x0)
	C:/Users/xxxx/Documents/workspace/am-repport/pdf/wkHtmlGenerator.go:44 +0x42b
am-repport/report.(*AcctStrcReporter).ToPdf(0xc00024a090, 0x0, 0x0, 0x0, 0x0)
	C:/Users/xxxx/Documents/workspace/am-repport/report/acctStrcReporter.go:132 +0x8d
main.main()
	C:/Users/xxxx/Documents/workspace/am-repport/main.go:41 +0x40b

goroutine 19 [select]:
database/sql.(*DB).connectionOpener(0xc00008da00, 0x7ff771fd4838, 0xc0000f5f40)
	C:/Users/xxxx/Go/src/database/sql/sql.go:1133 +0xbc
created by database/sql.OpenDB
	C:/Users/xxxx/Go/src/database/sql/sql.go:740 +0x132
rax     0x0
rbx     0x1f6db3bc900
rcx     0x0
rdi     0x1f6db35e7a0
rsi     0x0
rbp     0x75827feeb0
rsp     0x75827fecb8
r8      0x25
r9      0x66
r10     0x1f6db3bb580
r11     0x0
r12     0x0
r13     0x1f6db38bbb8
r14     0x1f6db3a7560
r15     0x0
rip     0x7ff8b6547110
rflags  0x10206
cs      0x33
fs      0x53
gs      0x2b

```

**Comment by adrg** [comment]
Does a basic example ran outside your application work for you? Something like:

```go
package main

import (
	"log"
	"os"

	pdf "github.com/adrg/go-wkhtmltopdf"
)

func main() {
	// Initialize library.
	if err := pdf.Init(); err != nil {
		log.Fatal(err)
	}
	defer pdf.Destroy()

	// Create object from URL.
	object, err := pdf.NewObject("https://google.com")
	if err != nil {
		log.Fatal(err)
	}
	object.Footer.ContentLeft = "[date]"
	object.Footer.ContentCenter = "Sample footer information"
	object.Footer.ContentRight = "[page]"
	object.Footer.DisplaySeparator = true

	// Create converter.
	converter, err := pdf.NewConverter()
	if err != nil {
		log.Fatal(err)
	}
	defer converter.Destroy()

	// Add created objects to the converter.
	converter.Add(object)

	// Set converter options.
	converter.Title = "Sample document"
	converter.PaperSize = pdf.A4
	converter.Orientation = pdf.Landscape
	converter.MarginTop = "1cm"
	converter.MarginBottom = "1cm"
	converter.MarginLeft = "10mm"
	converter.MarginRight = "10mm"

	// Convert objects and save the output PDF document.
	outFile, err := os.Create("out.pdf")
	if err != nil {
		log.Fatal(err)
	}
	defer outFile.Close()

	if err := converter.Run(outFile); err != nil {
		log.Fatal(err)
	}
}
```

Also, are you running the conversion process inside a `goroutine` by any chance?
If so, see  https://github.com/adrg/go-wkhtmltopdf/tree/master/examples/http-server-advanced.

**Comment by rickdana** [comment]
I foud the issue. 

I was missing the Init call 

```
if err := pdf.Init(); err != nil {
		log.Fatal(err)
}
```

Thank for your help

**Comment by adrg** [comment]
No problem. I'm glad you solved the issue.
